##服务配合
server:
  port: 8080
  servlet:
    context-path: /online
    # 修改tomcat配置
    # 1、修改yml文件
    # 2、springboot2.0X以上定制ConfigurableServletWebServerFactory
  tomcat:
    threads:
      #最大线程数
      max: 150
      #最小线程数
      min-spare: 10
    uri-encoding: utf-8
    max-connections: 6000
#数据源配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/online_system?&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      name: testDruidDataSource
      initial-size: 5
      max-active: 20
      min-idle: 5
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 1000
      connection-properties: druid.stat.mergeSql=true
      max-wait: 6000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-return: false
      test-on-borrow: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        session-stat-enable: true
        session-stat-max-count: 10
        profile-enable: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: druid
        login-password: druid123456
        allow: 127.0.0.1
        deny:
      aop-patterns: com.online.system.aop.*
  #redis配置
  redis:
    host: 127.0.0.1
    password: cdn123456
    port: 7001
    database: 1
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: 1000
        min-idle: 1
        max-idle: 8
  #资源配置
  resources:
    static-locations: classpath:/webapp/public/,classpath:/webapp/static/
  #thymeleaf配置
  thymeleaf:
    cache: false
    servlet:
      content-type: text/html
    prefix: classpath:/webapp/public/
    mode: LEGACYHTML5
  mvc:
    static-path-pattern: /**
      #参数意义：
      #JsonInclude.Include.ALWAYS              默认
      #JsonInclude.Include.NON_DEFAULT     属性为默认值不序列化
    #JsonInclude.Include.NON_EMPTY         属性为 空（””） 或者为 NULL 都不序列化
    #JsonInclude.Include.NON_NULL           属性为NULL   不序列化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    # 设置属性命名策略,对应jackson下PropertyNamingStrategy中的常量值，SNAKE_CASE-返回的json驼峰式转下划线，json body下划线传到后端自动转驼峰式
    property-naming-strategy: SNAKE_CASE
    # 当地时区
    locale: zh
    default-property-inclusion: NON_NULL #不为空的属性才会序列化,具体属性可看JsonInclude.Include
    
#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:com/online/system/web/dao/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.online.system.web.entity
  global-config:
    #mybatis-plus 3.0+判空
    db-config:
       id-type: AUTO
   #   select-strategy: not_null
   #   insert-strategy: not_null
   #  update-strategy: not_null
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
logging:
  config: classpath:log4j2.xml
#版本号
version: V0.0.1
##文件服务器配置
minio:
  io:
    endpoint: http://127.0.0.1:9000
    accessKey: sparknet
    secretKey: sparknet123
    bucketName: zkxt
##jwt配置
config:
  jwt:
    # 加密密钥
    secret: onlinesystem-web
    # token有效时长
    expire: 3600
    # header 名称
    header: token